Report size of files to be uploaded
openaustralia/morph-cli pull request #12
Opened 2017-07-23 21:01 UTC by chris48s

Spotted there were a couple of low-hanging fruit issues open on this repo so thought I would have a go at them while teaching myself a bit of ruby.

Closes #5

2017-08-30 04:31 UTC, henare requested changes
This is neat @chris48s :sparkles: The approach seems fine to me but I'd like to request a change to the UX.

```
# What it looks like if there's no scraper.*:
henare@mana:~/Desktop rvm:(ruby-2.3.1) $ morph
Uploading and running...
Found 103.00 B...
Can't find scraper code. Expected to find a file called scraper.rb, scraper.php, scraper.py, scraper.pl, or scraper.js in the root directory

# If there is a typically-sized scraper.*:
henare@mana:~/Desktop rvm:(ruby-2.3.1) $ morph
Uploading and running...
Found 3.22 KiB...
Injecting configuration and compiling...
-----> Ruby app detected
[snip]

# If there's accidentally a really big file in the same directory:
henare@mana:~/Desktop rvm:(ruby-2.3.1) $ morph
Uploading and running...
Found 63.96 MiB...
^C/home/henare/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/openssl/buffering.rb:322:in `syswrite': Interrupt
```

I think the way the size information is presented to the user could be improved. A simple suggestion could be to change the first line to "Uploading 4 MiB..." which would then look like this in the example above:

```
henare@mana:~/Desktop rvm:(ruby-2.3.1) $ morph
Uploading 3.22 KiB...
Injecting configuration and compiling...
-----> Ruby app detected
[snip]
```

What do you think?

2017-08-30 19:37 UTC, chris48s commented
Cheers. Updated as requested

2017-08-31 23:39 UTC, henare approved these changes

2017-08-31 23:39 UTC, merged

2017-08-31 23:52 UTC, henare commented
Thanks @chris48s :star2: Released in 0.2.5 :tada: