Throw an error before uploading if there is no scraper file in the directory
openaustralia/morph-cli pull request #13
Opened 2017-07-23 21:03 UTC by chris48s

This one might have a merge conflict with #12
Let me know if I need to rebase

Closes #4

2017-08-30 04:14 UTC, henare submitted a review, later dismissed
[Edit: Accidentally marked this review as approved, see below for updated review].

2017-08-30 04:14 UTC, henare commented on lib/morph-cli.rb
> +    if not all_paths.find{ |file| /scraper\.[\S]+$/ =~ file }
In Ruby [use `!` instead of `not`](https://github.com/bbatsov/ruby-style-guide#bang-not-not).

2017-08-30 04:16 UTC, henare requested changes
Thanks for this contribution @chris48s! :tada: It looks good except for some small improvements.

Here's what it looks like if you run `morph` before this PR:

```
henare@mana:~/Desktop rvm:(ruby-2.3.1) $ morph
Uploading and running...
Can't find scraper code. Expected to find a file called scraper.rb, scraper.php, scraper.py, scraper.pl, or scraper.js in the root directory
henare@mana:~/Desktop rvm:(ruby-2.3.1) $ 
```

And after this PR:

```
henare@mana:~/Desktop rvm:(ruby-2.3.1) $ morph
Can't find scraper to upload.
henare@mana:~/Desktop rvm:(ruby-2.3.1) $ 
```

I think the error message in the before scenario is better so I think we should improve this before merging :smile: There's also a minor style change I've suggested.

2017-08-30 19:37 UTC, chris48s commented
Cheers. Updated as requested

2017-08-31 23:47 UTC, henare approved these changes

2017-08-31 23:47 UTC, merged

2017-08-31 23:52 UTC, henare commented
Thanks @chris48s :star2: Released in 0.2.5 :tada: